class LocationService {
  // Sample location data - in a real app, this would come from an API
  static final Map<String, Map<String, Map<String, List<String>>>> _locationData = {
    'Lebanon': {
      'Beirut': {
        'Beirut': [
          'Hamra Street',
          'Corniche Beirut',
          'Gemmayzeh Street',
          'Mar Mikhael',
          'Achrafieh',
          'Ras Beirut',
          'Downtown Beirut',
          'Verdun',
          'Manara',
          'Raouche',
          'Sodeco',
          'Tabaris',
          'Furn el Chebbak',
          'Mazraa',
          'Basta',
          'Bourj Hammoud',
          'Sin el Fil',
          'Hazmieh',
          'Chiyah',
          'Haret Hreik',
          'Ashrafieh',
          'Rmeil',
          'Mina el Hosn',
          'Sassine',
          'Monot',
          'Gouraud',
          'Sursock',
          'Rmeil',
          'Mina el Hosn',
          'Sassine Square',
          'Monot Street',
          'Gouraud Street'
        ]
      },
      'Mount Lebanon': {
        'Baabda': [
          'Baabda Main Street',
          'Hazmieh',
          'Chouf',
          'Aley',
          'Bhamdoun',
          'Deir el Qamar',
          'Beit ed-Dine',
          'Barouk',
          'Ain Zhalta',
          'Bmariam',
          'Kfarmatta',
          'Kfarnabrakh',
          'Baabda Palace',
          'Chouf Cedar Reserve',
          'Beit ed-Dine Palace',
          'Deir el Qamar Square',
          'Moussa Castle',
          'Ain Zhalta Waterfall',
          'Barouk Mountain',
          'Bhamdoun Station',
          'Aley Main Street',
          'Chouf Mountains'
        ],
        'Jounieh': [
          'Jounieh Bay',
          'Maameltein',
          'Harissa',
          'Zouk Mikael',
          'Dbayeh',
          'Zouk Mosbeh',
          'Nahr el-Kalb',
          'Tabarja',
          'Faitroun',
          'Ghazir',
          'Bikfaya',
          'Bhamdoun el-Mhatta',
          'Jounieh Port',
          'Our Lady of Lebanon',
          'Teleferique',
          'Kaslik',
          'Antelias',
          'Dbayeh Marina',
          'Zouk Mosbeh Beach',
          'Nahr el-Kalb Bridge',
          'Tabarja Beach',
          'Faitroun Village',
          'Ghazir Palace',
          'Bikfaya Main Street'
        ],
        'Keserwan': [
          'Jbeil',
          'Byblos',
          'Jbeil Port',
          'Byblos Castle',
          'Old Souk',
          'Wax Museum',
          'St. John Church',
          'Temple of Baalat Gebal',
          'Byblos Archaeological Site',
          'Jbeil Marina',
          'Byblos Beach',
          'Jbeil Main Street',
          'Byblos Souk',
          'Jbeil Castle',
          'Byblos Port'
        ],
        'Metn': [
          'Antelias',
          'Bourj Hammoud',
          'Sin el Fil',
          'Hazmieh',
          'Chiyah',
          'Haret Hreik',
          'Antelias Main Street',
          'Bourj Hammoud Market',
          'Sin el Fil Square',
          'Hazmieh Palace',
          'Chiyah Center',
          'Haret Hreik Main Street',
          'Antelias Port',
          'Bourj Hammoud Bridge',
          'Sin el Fil Station'
        ]
      },
      'North Lebanon': {
        'Tripoli': [
          'Tripoli Port',
          'Al Mina',
          'El Tall',
          'Abu Samra',
          'Qalamoun',
          'Al Qobbeh',
          'Al Zahriyah',
          'Al Mankoubin',
          'Al Ghorba',
          'Al Haddadin',
          'Al Qalamoun',
          'Al Mina Port',
          'Tripoli Citadel',
          'Al Mina Souk',
          'El Tall Square',
          'Abu Samra Market',
          'Qalamoun Beach',
          'Al Qobbeh Mosque',
          'Al Zahriyah Street',
          'Al Mankoubin Quarter',
          'Al Ghorba Area',
          'Al Haddadin Street',
          'Tripoli Clock Tower',
          'Al Mina Corniche'
        ],
        'Zgharta': [
          'Zgharta Center',
          'Ehden',
          'Bsharri',
          'Koura',
          'Amioun',
          'Kfarhazir',
          'Kfarhata',
          'Kfarzina',
          'Kfarhbab',
          'Zgharta Main Street',
          'Ehden Forest',
          'Bsharri Cedars',
          'Koura Valley',
          'Amioun Square',
          'Kfarhazir Village',
          'Kfarhata Center',
          'Kfarzina Street',
          'Kfarhbab Area',
          'Ehden Mountain',
          'Bsharri Cedar Reserve',
          'Koura Hills',
          'Amioun Market'
        ],
        'Akkar': [
          'Halba',
          'Akkar Center',
          'Qobayat',
          'Fneideq',
          'Halba Main Street',
          'Akkar Castle',
          'Qobayat Village',
          'Fneideq Port',
          'Halba Market',
          'Akkar Mountains',
          'Qobayat Valley',
          'Fneideq Beach',
          'Halba Square',
          'Akkar Forest',
          'Qobayat Hills',
          'Fneideq Marina'
        ],
        'Koura': [
          'Amioun',
          'Koura Center',
          'Kfarhazir',
          'Kfarhata',
          'Kfarzina',
          'Kfarhbab',
          'Amioun Main Street',
          'Koura Valley',
          'Kfarhazir Village',
          'Kfarhata Center',
          'Kfarzina Street',
          'Kfarhbab Area',
          'Amioun Square',
          'Koura Hills',
          'Kfarhazir Market',
          'Kfarhata Village'
        ]
      },
      'South Lebanon': {
        'Sidon': [
          'Sidon Port',
          'Old City',
          'Sidon Castle',
          'Ain al-Hilweh',
          'Mieh Mieh',
          'Abu al-Aswad',
          'Al Ghaziyah',
          'Al Kafr',
          'Al Kafr al-Jawzi',
          'Al Kafr al-Miski',
          'Al Kafr al-Sawda',
          'Al Kafr al-Zayt',
          'Sidon Souk',
          'Sidon Sea Castle',
          'Ain al-Hilweh Camp',
          'Mieh Mieh Beach',
          'Abu al-Aswad Quarter',
          'Al Ghaziyah Street',
          'Al Kafr Village',
          'Sidon Corniche',
          'Sidon Museum',
          'Sidon Port Area'
        ],
        'Tyre': [
          'Tyre Port',
          'Al Mina',
          'Rashidieh',
          'Qana',
          'Al Qulaylah',
          'Al Jibbayn',
          'Al Mansouri',
          'Tyre Archaeological Site',
          'Tyre Hippodrome',
          'Tyre Cathedral',
          'Al Mina Beach',
          'Rashidieh Camp',
          'Qana Village',
          'Al Qulaylah Quarter',
          'Al Jibbayn Street',
          'Al Mansouri Area',
          'Tyre Souk',
          'Tyre Corniche',
          'Tyre Port Area'
        ],
        'Nabatieh': [
          'Nabatieh Center',
          'Jezzine',
          'Marjayoun',
          'Hasbaya',
          'Rashaya',
          'Nabatieh Main Street',
          'Jezzine Waterfall',
          'Marjayoun Castle',
          'Hasbaya Palace',
          'Rashaya Citadel',
          'Nabatieh Market',
          'Jezzine Valley',
          'Marjayoun Square',
          'Hasbaya Center',
          'Rashaya Village',
          'Nabatieh Souk'
        ],
        'Jezzine': [
          'Jezzine Center',
          'Jezzine Waterfall',
          'Jezzine Valley',
          'Jezzine Main Street',
          'Jezzine Market',
          'Jezzine Square',
          'Jezzine Forest',
          'Jezzine Mountains',
          'Jezzine Village',
          'Jezzine Souk'
        ]
      },
      'Bekaa': {
        'Zahle': [
          'Zahle Center',
          'Chtaura',
          'Anjar',
          'Zahle Main Street',
          'Chtaura Junction',
          'Anjar Archaeological Site',
          'Zahle Market',
          'Chtaura Square',
          'Anjar Castle',
          'Zahle Souk',
          'Chtaura Station',
          'Anjar Village',
          'Zahle Valley',
          'Chtaura Center',
          'Anjar Main Street'
        ],
        'Baalbek': [
          'Baalbek Temples',
          'Baalbek Center',
          'Baalbek Archaeological Site',
          'Temple of Jupiter',
          'Temple of Bacchus',
          'Temple of Venus',
          'Baalbek Citadel',
          'Baalbek Museum',
          'Baalbek Main Street',
          'Baalbek Market',
          'Baalbek Square',
          'Baalbek Souk',
          'Baalbek Valley',
          'Baalbek Hills'
        ],
        'Hermel': [
          'Hermel Center',
          'Hermel Main Street',
          'Hermel Market',
          'Hermel Square',
          'Hermel Village',
          'Hermel Souk',
          'Hermel Valley',
          'Hermel Mountains',
          'Hermel Forest',
          'Hermel Area'
        ],
        'Rashaya': [
          'Rashaya Citadel',
          'Rashaya Center',
          'Rashaya Main Street',
          'Rashaya Market',
          'Rashaya Square',
          'Rashaya Village',
          'Rashaya Souk',
          'Rashaya Valley',
          'Rashaya Mountains',
          'Rashaya Forest'
        ],
        'Western Bekaa': [
          'Chtaura',
          'Western Bekaa Center',
          'Chtaura Junction',
          'Western Bekaa Valley',
          'Chtaura Square',
          'Western Bekaa Market',
          'Chtaura Station',
          'Western Bekaa Souk',
          'Chtaura Center',
          'Western Bekaa Main Street'
        ]
      }
    },
    'Syria': {
      'Damascus': {
        'Damascus': [
          'Old City',
          'Umayyad Mosque',
          'Straight Street',
          'Souk al-Hamidiyah',
          'Azem Palace',
          'National Museum',
          'Damascus Citadel',
          'Saladin Tomb',
          'Ananias Chapel',
          'St. Paul Chapel',
          'Damascus University',
          'Tishreen Park',
          'Abu Rummaneh',
          'Malki',
          'Mazzeh',
          'Kafr Sousa',
          'Dummar',
          'Barzeh',
          'Qaboun',
          'Jobar'
        ]
      },
      'Aleppo': {
        'Aleppo': [
          'Aleppo Citadel',
          'Old City',
          'Souk al-Madina',
          'Great Mosque',
          'Khan al-Wazir',
          'Khan al-Saboun',
          'Aleppo University',
          'Aziziyeh Square',
          'Saadallah al-Jabiri Square',
          'Al-Hamidiyah Souk',
          'Al-Madina Souk',
          'Al-Zirb Market',
          'Al-Attarine Souk',
          'Al-Saqatiyya Souk',
          'Al-Herafiyyin Souk',
          'Al-Saboun Souk',
          'Al-Nahhasin Souk',
          'Al-Dabbagha Souk',
          'Al-Sagha Souk',
          'Al-Khandaq Souk'
        ]
      },
      'Homs': {
        'Homs': [
          'Homs Center',
          'Khalid ibn al-Walid Mosque',
          'Old City',
          'Homs Citadel',
          'Al-Zahra Square',
          'Al-Hamidiya Market',
          'Al-Souk al-Kabir',
          'Al-Souk al-Saghir',
          'Al-Khandaq Street',
          'Al-Qusour',
          'Al-Waer',
          'Al-Baath University',
          'Homs University',
          'Al-Ghouta',
          'Al-Rastan',
          'Al-Qusayr',
          'Al-Mukharram',
          'Al-Qaryatayn',
          'Al-Salamiyah',
          'Al-Mahin'
        ]
      },
      'Latakia': {
        'Latakia': [
          'Latakia Port',
          'Corniche',
          'Latakia University',
          'Al-Salam Square',
          'Al-Mina',
          'Al-Raml al-Janoubi',
          'Al-Raml al-Shamali',
          'Al-Aziziyah',
          'Al-Shaab',
          'Al-Quds',
          'Al-Nuzha',
          'Al-Mahatta',
          'Al-Sinaa',
          'Al-Hamra',
          'Al-Saboun',
          'Al-Kindi',
          'Al-Maamoun',
          'Al-Rashideen',
          'Al-Salam',
          'Al-Nour'
        ]
      }
    },
    'Jordan': {
      'Amman': {
        'Amman': [
          'Downtown Amman',
          'Citadel Hill',
          'Roman Theater',
          'King Abdullah Mosque',
          'King Hussein Mosque',
          'Amman Citadel',
          'Temple of Hercules',
          'Ummayad Palace',
          'Archaeological Museum',
          'Rainbow Street',
          'Abdoun',
          'Jabal Amman',
          'Jabal Luweibdeh',
          'Jabal al-Ashrafieh',
          'Jabal al-Hussein',
          'Jabal al-Nasr',
          'Jabal al-Taj',
          'Jabal al-Qalaa',
          'Jabal al-Weibdeh',
          'Jabal al-Ahliyah'
        ]
      },
      'Irbid': {
        'Irbid': [
          'Irbid Center',
          'Yarmouk University',
          'Irbid Castle',
          'Al-Hussein Bin Talal University',
          'Irbid Museum',
          'Al-Mazar al-Janoubi',
          'Al-Mazar al-Shamali',
          'Al-Kourah',
          'Al-Taybeh',
          'Al-Ramtha',
          'Al-Hashmiyah',
          'Al-Sareeh',
          'Al-Mashariq',
          'Al-Mafraq',
          'Al-Zarqa',
          'Al-Balqa',
          'Al-Karak',
          'Al-Tafilah',
          'Al-Aqaba',
          'Al-Ma\'an'
        ]
      },
      'Zarqa': {
        'Zarqa': [
          'Zarqa Center',
          'Zarqa University',
          'Al-Hashmiyah',
          'Al-Sukhna',
          'Al-Azraq',
          'Al-Ruwaished',
          'Al-Mafraq',
          'Al-Zarqa Industrial City',
          'Al-Hashmiyah Industrial City',
          'Al-Sukhna Industrial City',
          'Al-Azraq Industrial City',
          'Al-Ruwaished Industrial City',
          'Al-Mafraq Industrial City',
          'Al-Zarqa Free Zone',
          'Al-Hashmiyah Free Zone',
          'Al-Sukhna Free Zone',
          'Al-Azraq Free Zone',
          'Al-Ruwaished Free Zone',
          'Al-Mafraq Free Zone',
          'Al-Zarqa Port'
        ]
      }
    },
    'Egypt': {
      'Cairo': {
        'Cairo': [
          'Tahrir Square',
          'Egyptian Museum',
          'Khan el-Khalili',
          'Al-Azhar Mosque',
          'Sultan Hassan Mosque',
          'Al-Rifai Mosque',
          'Cairo Citadel',
          'Mohamed Ali Mosque',
          'Coptic Cairo',
          'Hanging Church',
          'St. George Church',
          'Ben Ezra Synagogue',
          'Islamic Cairo',
          'Al-Muizz Street',
          'Al-Darb al-Ahmar',
          'Al-Gamaliya',
          'Al-Darb al-Asfar',
          'Al-Sayeda Zeinab',
          'Al-Sayeda Aisha',
          'Al-Hussein'
        ]
      },
      'Alexandria': {
        'Alexandria': [
          'Corniche',
          'Qaitbay Citadel',
          'Bibliotheca Alexandrina',
          'Pompey\'s Pillar',
          'Catacombs of Kom el Shoqafa',
          'Montaza Palace',
          'Stanley Bridge',
          'Al-Montazah',
          'Al-Maamoura',
          'Al-Shatby',
          'Al-Gleem',
          'Al-Smouha',
          'Al-Raml',
          'Al-Attarin',
          'Al-Mansheya',
          'Al-Gomrok',
          'Al-Laban',
          'Al-Max',
          'Al-Agamy',
          'Al-Dekheila'
        ]
      },
      'Giza': {
        'Giza': [
          'Giza Pyramids',
          'Great Sphinx',
          'Pyramid of Khufu',
          'Pyramid of Khafre',
          'Pyramid of Menkaure',
          'Solar Boat Museum',
          'Giza Plateau',
          'Nile Valley',
          'Giza Zoo',
          'Orman Garden',
          'Giza Corniche',
          'Al-Haram',
          'Al-Dokki',
          'Al-Mohandessin',
          'Al-Agouza',
          'Al-Imbaba',
          'Al-Warraq',
          'Al-Kitkat',
          'Al-Boulaq',
          'Al-Zamalek'
        ]
      }
    },
    'Saudi Arabia': {
      'Riyadh': {
        'Riyadh': [
          'King Fahd Road',
          'King Abdullah Road',
          'King Salman Road',
          'Olaya Street',
          'Tahlia Street',
          'King Khalid Road',
          'King Abdulaziz Road',
          'King Faisal Road',
          'King Saud Road',
          'King Khalid International Airport Road',
          'King Fahd Medical City Road',
          'King Abdulaziz Medical City Road',
          'King Faisal Medical City Road',
          'King Saud Medical City Road',
          'King Khalid Medical City Road',
          'King Fahd Medical City Road',
          'King Abdulaziz Medical City Road',
          'King Faisal Medical City Road',
          'King Saud Medical City Road',
          'King Khalid Medical City Road'
        ]
      },
      'Jeddah': {
        'Jeddah': [
          'King Abdulaziz Road',
          'King Fahd Road',
          'King Abdullah Road',
          'Corniche Road',
          'Al Hamra Street',
          'Al Balad',
          'Al Hamra',
          'Al Zahra',
          'Al Salamah',
          'Al Rawdah',
          'Al Andalus',
          'Al Malaz',
          'Al Sahafah',
          'Al Naeem',
          'Al Rehab',
          'Al Faisaliyah',
          'Al Shati',
          'Al Corniche',
          'Al Hamra',
          'Al Zahra'
        ]
      },
      'Mecca': {
        'Mecca': [
          'King Abdulaziz Road',
          'King Fahd Road',
          'Al Haram Street',
          'Al Aziziyah',
          'Al Misfalah',
          'Al Shubaikah',
          'Al Taneem',
          'Al Adl',
          'Al Shafaa',
          'Al Marwa',
          'Al Haram',
          'Al Aziziyah',
          'Al Misfalah',
          'Al Shubaikah',
          'Al Taneem',
          'Al Adl',
          'Al Shafaa',
          'Al Marwa',
          'Al Haram',
          'Al Aziziyah'
        ]
      },
      'Medina': {
        'Medina': [
          'King Fahd Road',
          'King Abdullah Road',
          'Al Haram Street',
          'Al Anbariyah',
          'Al Awali',
          'Al Qiblatain',
          'Al Quba',
          'Al Uhud',
          'Al Quba',
          'Al Uhud',
          'Al Anbariyah',
          'Al Awali',
          'Al Qiblatain',
          'Al Quba',
          'Al Uhud',
          'Al Anbariyah',
          'Al Awali',
          'Al Qiblatain',
          'Al Quba',
          'Al Uhud'
        ]
      }
    },
    'United Arab Emirates': {
      'Dubai': {
        'Dubai': [
          'Sheikh Zayed Road',
          'Jumeirah Beach Road',
          'Al Wasl Road',
          'Al Khaleej Street',
          'Al Maktoum Street',
          'Al Dhiyafah Street',
          'Al Wasl Street',
          'Al Thanya Street',
          'Al Qudra Road',
          'Emirates Road',
          'Al Meydan Road',
          'Al Khail Road',
          'Al Asayel Street',
          'Al Hadiqa Street',
          'Al Safa Street',
          'Al Manara Street',
          'Al Wasl Street',
          'Al Thanya Street',
          'Al Qudra Road',
          'Emirates Road'
        ],
        'Jumeirah': [
          'Jumeirah Beach Road',
          'Jumeirah Road',
          'Al Wasl Road',
          'Al Thanya Street',
          'Al Qudra Road',
          'Al Safa Street',
          'Al Manara Street',
          'Al Wasl Street',
          'Al Thanya Street',
          'Al Qudra Road',
          'Jumeirah Beach Road',
          'Jumeirah Road'
        ],
        'Palm Jumeirah': [
          'Palm Jumeirah Road',
          'Palm Tower Road',
          'Atlantis Road',
          'Palm West Beach',
          'Palm East Beach',
          'Palm Central',
          'Palm Gateway',
          'Palm Crescent',
          'Palm Trunk',
          'Palm Fronds',
          'Palm Shoreline',
          'Palm Marina'
        ]
      },
      'Abu Dhabi': {
        'Abu Dhabi': [
          'Corniche Road',
          'Sheikh Zayed Street',
          'Al Salam Street',
          'Al Falah Street',
          'Al Najda Street',
          'Al Markaziyah',
          'Al Zahiyah',
          'Al Bateen',
          'Al Mushrif',
          'Al Karamah',
          'Al Ras Al Akhdar',
          'Al Qurm',
          'Al Khalidiyah',
          'Al Bateen',
          'Al Mushrif',
          'Al Karamah',
          'Al Ras Al Akhdar',
          'Al Qurm',
          'Al Khalidiyah',
          'Al Bateen'
        ],
        'Al Ain': [
          'Al Ain Road',
          'Al Jimi',
          'Al Qattara',
          'Al Hili',
          'Al Buraimi',
          'Al Muwaiji',
          'Al Jahili',
          'Al Qattara',
          'Al Hili',
          'Al Buraimi',
          'Al Muwaiji',
          'Al Jahili'
        ]
      },
      'Sharjah': {
        'Sharjah': [
          'Al Wahda Street',
          'King Faisal Street',
          'Al Ittihad Street',
          'Al Arouba Street',
          'Al Khan Street',
          'Al Majaz',
          'Al Qasba',
          'Al Nahda',
          'Al Taawun',
          'Al Rolla',
          'Al Qasba',
          'Al Nahda',
          'Al Taawun',
          'Al Rolla',
          'Al Majaz',
          'Al Khan',
          'Al Arouba',
          'Al Ittihad',
          'King Faisal',
          'Al Wahda'
        ]
      },
      'Ajman': {
        'Ajman': [
          'Sheikh Humaid Street',
          'Al Nuaimiya',
          'Al Rashidiya',
          'Al Mowaihat',
          'Al Zahra',
          'Al Rawda',
          'Al Hamriya',
          'Al Bustan',
          'Al Jerf',
          'Al Muntazah',
          'Al Nuaimiya',
          'Al Rashidiya'
        ]
      }
    },
    'United States': {
      'California': {
        'Los Angeles': [
          'Hollywood Boulevard',
          'Sunset Boulevard',
          'Wilshire Boulevard',
          'Santa Monica Boulevard',
          'Ventura Boulevard',
          'Melrose Avenue',
          'Beverly Hills',
          'Venice Beach',
          'Santa Monica',
          'Pasadena',
          'Downtown LA',
          'Echo Park',
          'Silver Lake',
          'Los Feliz',
          'Atwater Village',
          'Glendale',
          'Burbank',
          'Culver City',
          'Marina del Rey',
          'Manhattan Beach'
        ],
        'San Francisco': [
          'Market Street',
          'Mission Street',
          'Geary Boulevard',
          'Van Ness Avenue',
          'Lombard Street',
          'Fisherman\'s Wharf',
          'Alcatraz',
          'Golden Gate Bridge',
          'Chinatown',
          'North Beach',
          'Marina District',
          'Pacific Heights',
          'Nob Hill',
          'Russian Hill',
          'Telegraph Hill',
          'Financial District',
          'SOMA',
          'Hayes Valley',
          'Castro District',
          'Mission District'
        ],
        'San Diego': [
          'Gaslamp Quarter',
          'Seaport Village',
          'Balboa Park',
          'La Jolla',
          'Coronado',
          'Mission Beach',
          'Pacific Beach',
          'Ocean Beach',
          'Point Loma',
          'Old Town',
          'Downtown San Diego',
          'Little Italy',
          'East Village',
          'North Park',
          'South Park',
          'Hillcrest',
          'University Heights',
          'Normal Heights',
          'Kensington',
          'Talmadge'
        ]
      },
      'New York': {
        'New York City': [
          'Broadway',
          'Fifth Avenue',
          'Park Avenue',
          'Madison Avenue',
          'Lexington Avenue',
          'Times Square',
          'Central Park',
          'Brooklyn Bridge',
          'Wall Street',
          'Harlem',
          'Upper East Side',
          'Upper West Side',
          'Midtown Manhattan',
          'Lower Manhattan',
          'Chelsea',
          'Greenwich Village',
          'SoHo',
          'Tribeca',
          'Financial District',
          'Battery Park'
        ],
        'Buffalo': [
          'Main Street',
          'Elmwood Avenue',
          'Delaware Avenue',
          'Chippewa Street',
          'Allen Street',
          'Allentown',
          'Elmwood Village',
          'North Buffalo',
          'South Buffalo',
          'West Side',
          'East Side',
          'Black Rock',
          'Riverside',
          'University Heights',
          'Kensington',
          'Lovejoy',
          'Fillmore',
          'Grant',
          'Bailey',
          'Seneca'
        ]
      },
      'Texas': {
        'Houston': [
          'Main Street',
          'Westheimer Road',
          'Kirby Drive',
          'Richmond Avenue',
          'Washington Avenue',
          'Montrose',
          'Rice Village',
          'Galleria',
          'Museum District',
          'Heights',
          'Midtown',
          'Downtown Houston',
          'Medical Center',
          'River Oaks',
          'Memorial',
          'Spring Branch',
          'Katy',
          'Sugar Land',
          'The Woodlands',
          'Cypress'
        ],
        'Austin': [
          'Congress Avenue',
          'Sixth Street',
          'Lamar Boulevard',
          'Guadalupe Street',
          'Burnet Road',
          'Downtown Austin',
          'East Austin',
          'West Austin',
          'South Austin',
          'North Austin',
          'Zilker',
          'Barton Springs',
          'Travis Heights',
          'Hyde Park',
          'Clarksville',
          'Tarrytown',
          'Westlake',
          'Lake Travis',
          'Round Rock',
          'Cedar Park'
        ],
        'Dallas': [
          'Main Street',
          'Oak Lawn Avenue',
          'Greenville Avenue',
          'McKinney Avenue',
          'Deep Ellum',
          'Uptown',
          'Downtown Dallas',
          'Bishop Arts District',
          'Trinity Groves',
          'Design District',
          'Victory Park',
          'Arts District',
          'West End',
          'Cedar Springs',
          'Knox-Henderson',
          'Lower Greenville',
          'Lakewood',
          'M Streets',
          'Preston Hollow',
          'Highland Park'
        ]
      },
      'Florida': {
        'Miami': [
          'Ocean Drive',
          'Collins Avenue',
          'Washington Avenue',
          'Lincoln Road',
          'South Beach',
          'North Beach',
          'Mid-Beach',
          'Downtown Miami',
          'Brickell',
          'Coconut Grove',
          'Coral Gables',
          'Key Biscayne',
          'Miami Beach',
          'Wynwood',
          'Design District',
          'Little Havana',
          'Calle Ocho',
          'Bayside',
          'Bayfront Park',
          'Vizcaya'
        ],
        'Orlando': [
          'International Drive',
          'Orange Blossom Trail',
          'Colonial Drive',
          'Mills Avenue',
          'Downtown Orlando',
          'Winter Park',
          'Thornton Park',
          'College Park',
          'Audubon Park',
          'Baldwin Park',
          'Lake Nona',
          'Dr. Phillips',
          'Windermere',
          'Celebration',
          'Kissimmee',
          'Lake Buena Vista',
          'Universal Studios',
          'Disney World',
          'SeaWorld',
          'Legoland'
        ]
      }
    },
    'Turkey': {
      'Istanbul': {
        'Istanbul': [
          'Sultanahmet',
          'Taksim Square',
          'Galata Tower',
          'Hagia Sophia',
          'Blue Mosque',
          'Topkapi Palace',
          'Grand Bazaar',
          'Spice Bazaar',
          'Bosphorus Bridge',
          'Ortakoy',
          'Beyoglu',
          'Kadikoy',
          'Uskudar',
          'Besiktas',
          'Sisli',
          'Levent',
          'Maslak',
          'Etiler',
          'Ulus',
          'Bebek'
        ]
      },
      'Ankara': {
        'Ankara': [
          'Kizilay',
          'Ulus',
          'Cankaya',
          'Kocatepe Mosque',
          'Anitkabir',
          'Atakule',
          'Ankara Castle',
          'Museum of Anatolian Civilizations',
          'Genclik Park',
          'Tunali Hilmi',
          'Bahcelievler',
          'Kizilcahamam',
          'Beypazari',
          'Polatli',
          'Sincan',
          'Etimesgut',
          'Mamak',
          'Kecioren',
          'Yenimahalle',
          'Pursaklar'
        ]
      },
      'Izmir': {
        'Izmir': [
          'Konak',
          'Alsancak',
          'Karsiyaka',
          'Bornova',
          'Buca',
          'Gaziemir',
          'Balcova',
          'Narlidere',
          'Guzelbahce',
          'Menderes',
          'Torbali',
          'Menemen',
          'Aliağa',
          'Foça',
          'Cesme',
          'Kusadasi',
          'Selcuk',
          'Tire',
          'Bayindir',
          'Kemalpasa'
        ]
      }
    },
    'France': {
      'Paris': {
        'Paris': [
          'Champs-Élysées',
          'Eiffel Tower',
          'Louvre Museum',
          'Notre-Dame',
          'Arc de Triomphe',
          'Montmartre',
          'Sacré-Cœur',
          'Place de la Concorde',
          'Tuileries Garden',
          'Luxembourg Garden',
          'Marais',
          'Le Marais',
          'Saint-Germain-des-Prés',
          'Latin Quarter',
          'Bastille',
          'Canal Saint-Martin',
          'Belleville',
          'Ménilmontant',
          'Buttes-Chaumont',
          'Parc des Buttes-Chaumont'
        ]
      },
      'Lyon': {
        'Lyon': [
          'Vieux Lyon',
          'Place Bellecour',
          'Fourvière Basilica',
          'Lyon Cathedral',
          'Traboules',
          'Presqu\'île',
          'Croix-Rousse',
          'Confluence',
          'Part-Dieu',
          'Gerland',
          'Villeurbanne',
          'Bron',
          'Vénissieux',
          'Saint-Fons',
          'Caluire-et-Cuire',
          'Rillieux-la-Pape',
          'Décines-Charpieu',
          'Meyzieu',
          'Vaulx-en-Velin',
          'Saint-Priest'
        ]
      },
      'Marseille': {
        'Marseille': [
          'Vieux Port',
          'Notre-Dame de la Garde',
          'Le Panier',
          'La Canebière',
          'Rue de la République',
          'Rue d\'Antibes',
          'Promenade des Anglais',
          'Corniche Kennedy',
          'Calanques',
          'Château d\'If',
          'MuCEM',
          'Palais Longchamp',
          'Cours Julien',
          'La Plaine',
          'Noailles',
          'Belsunce',
          'Saint-Charles',
          'La Blancarde',
          'La Timone',
          'La Valentine'
        ]
      }
    },
    'Germany': {
      'Berlin': {
        'Berlin': [
          'Brandenburg Gate',
          'Reichstag',
          'Checkpoint Charlie',
          'Potsdamer Platz',
          'Alexanderplatz',
          'Unter den Linden',
          'Friedrichstraße',
          'Kurfürstendamm',
          'Potsdamer Straße',
          'Leipziger Straße',
          'Mitte',
          'Kreuzberg',
          'Friedrichshain',
          'Prenzlauer Berg',
          'Neukölln',
          'Schöneberg',
          'Charlottenburg',
          'Wilmersdorf',
          'Steglitz',
          'Zehlendorf'
        ]
      },
      'Munich': {
        'Munich': [
          'Marienplatz',
          'Frauenkirche',
          'Viktualienmarkt',
          'Hofbräuhaus',
          'English Garden',
          'Nymphenburg Palace',
          'Residenz',
          'Alte Pinakothek',
          'Neue Pinakothek',
          'Pinakothek der Moderne',
          'Maximilianstraße',
          'Kaufingerstraße',
          'Neuhauser Straße',
          'Odeonsplatz',
          'Karlsplatz',
          'Sendlinger Straße',
          'Theatinerstraße',
          'Residenzstraße',
          'Bayerstraße',
          'Altstadt'
        ]
      },
      'Hamburg': {
        'Hamburg': [
          'Speicherstadt',
          'HafenCity',
          'Elbphilharmonie',
          'Reeperbahn',
          'St. Pauli',
          'Alster',
          'Jungfernstieg',
          'Rathausmarkt',
          'Mönckebergstraße',
          'Spitalerstraße',
          'Neustadt',
          'Altstadt',
          'Sternschanze',
          'Schanzenviertel',
          'Karolinenviertel',
          'Ottensen',
          'Altona',
          'Eimsbüttel',
          'Winterhude',
          'Uhlenhorst'
        ]
      }
    },
    'Italy': {
      'Rome': {
        'Rome': [
          'Colosseum',
          'Roman Forum',
          'Pantheon',
          'Trevi Fountain',
          'Spanish Steps',
          'Vatican City',
          'St. Peter\'s Basilica',
          'Sistine Chapel',
          'Vatican Museums',
          'Castel Sant\'Angelo',
          'Trastevere',
          'Campo de\' Fiori',
          'Piazza Navona',
          'Piazza del Popolo',
          'Via del Corso',
          'Via Veneto',
          'Testaccio',
          'Monti',
          'Pigneto',
          'San Lorenzo'
        ]
      },
      'Milan': {
        'Milan': [
          'Duomo di Milano',
          'Galleria Vittorio Emanuele II',
          'La Scala',
          'Sforza Castle',
          'Brera',
          'Navigli',
          'Porta Nuova',
          'Corso Buenos Aires',
          'Via Montenapoleone',
          'Quadrilatero della Moda',
          'Isola',
          'Garibaldi',
          'Porta Garibaldi',
          'Corso Como',
          'Via Torino',
          'Via Dante',
          'Piazza del Duomo',
          'Piazza della Scala',
          'Piazza Castello',
          'Piazza Gae Aulenti'
        ]
      },
      'Florence': {
        'Florence': [
          'Duomo',
          'Uffizi Gallery',
          'Ponte Vecchio',
          'Pitti Palace',
          'Boboli Gardens',
          'Piazza della Signoria',
          'Ponte Santa Trinita',
          'Ponte alle Grazie',
          'Ponte Amerigo Vespucci',
          'Ponte San Niccolò',
          'Oltrarno',
          'Santo Spirito',
          'San Frediano',
          'San Niccolò',
          'Santa Croce',
          'Santa Maria Novella',
          'Duomo',
          'Baptistery',
          'Campanile',
          'Cupola'
        ]
      }
    },
    'Spain': {
      'Madrid': {
        'Madrid': [
          'Puerta del Sol',
          'Plaza Mayor',
          'Royal Palace',
          'Prado Museum',
          'Retiro Park',
          'Gran Vía',
          'Salamanca',
          'Chueca',
          'Malasaña',
          'Lavapiés',
          'La Latina',
          'Huertas',
          'Antón Martín',
          'Tirso de Molina',
          'Ópera',
          'Callao',
          'Moncloa',
          'Argüelles',
          'Chamberí',
          'Tetuán'
        ]
      },
      'Barcelona': {
        'Barcelona': [
          'Sagrada Familia',
          'Park Güell',
          'Casa Batlló',
          'Casa Milà',
          'Las Ramblas',
          'Gothic Quarter',
          'El Born',
          'Barceloneta',
          'Eixample',
          'Gràcia',
          'Poblenou',
          'Sant Antoni',
          'Raval',
          'Poble Sec',
          'Sants',
          'Les Corts',
          'Sarrià-Sant Gervasi',
          'Horta-Guinardó',
          'Nou Barris',
          'Sant Andreu'
        ]
      },
      'Valencia': {
        'Valencia': [
          'Ciudad de las Artes y las Ciencias',
          'Oceanogràfic',
          'Mercado Central',
          'Lonja de la Seda',
          'Cathedral',
          'Miguelete Tower',
          'Plaza de la Virgen',
          'Plaza de la Reina',
          'Plaza del Ayuntamiento',
          'Plaza de Toros',
          'Ruzafa',
          'El Carmen',
          'Eixample',
          'Campanar',
          'Benimaclet',
          'Patraix',
          'Jesús',
          'Nazaret',
          'Poblats Marítims',
          'Poblats del Nord'
        ]
      }
    },
    'United Kingdom': {
      'England': {
        'London': [
          'Oxford Street',
          'Regent Street',
          'Bond Street',
          'Piccadilly',
          'Carnaby Street',
          'Covent Garden',
          'Soho',
          'Mayfair',
          'Chelsea',
          'Camden',
          'Notting Hill',
          'Kensington',
          'Knightsbridge',
          'Belgravia',
          'Marylebone',
          'Fitzrovia',
          'Bloomsbury',
          'Holborn',
          'Clerkenwell',
          'Shoreditch'
        ],
        'Manchester': [
          'Market Street',
          'Deansgate',
          'Oxford Road',
          'Wilmslow Road',
          'Rusholme',
          'Northern Quarter',
          'Spinningfields',
          'Castlefield',
          'Ancoats',
          'Didsbury',
          'Chorlton',
          'Withington',
          'Fallowfield',
          'Hulme',
          'Moss Side',
          'Longsight',
          'Levenshulme',
          'Burnage',
          'Withington',
          'Didsbury'
        ],
        'Birmingham': [
          'New Street',
          'High Street',
          'Corporation Street',
          'Bull Street',
          'Colmore Row',
          'Digbeth',
          'Jewellery Quarter',
          'Gun Quarter',
          'Chinese Quarter',
          'Irish Quarter',
          'Gay Village',
          'Custard Factory',
          'Mailbox',
          'Brindleyplace',
          'Broad Street',
          'Hurst Street',
          'Moseley',
          'Kings Heath',
          'Selly Oak',
          'Edgbaston'
        ]
      },
      'Scotland': {
        'Edinburgh': [
          'Royal Mile',
          'Princes Street',
          'George Street',
          'Rose Street',
          'Grassmarket',
          'Old Town',
          'New Town',
          'Leith',
          'Stockbridge',
          'Morningside',
          'Bruntsfield',
          'Marchmont',
          'Tollcross',
          'Haymarket',
          'West End',
          'East End',
          'Portobello',
          'Musselburgh',
          'Dalkeith',
          'Penicuik'
        ],
        'Glasgow': [
          'Buchanan Street',
          'Sauchiehall Street',
          'Argyle Street',
          'Byres Road',
          'Great Western Road',
          'Merchant City',
          'West End',
          'East End',
          'South Side',
          'North Glasgow',
          'Finnieston',
          'Partick',
          'Hillhead',
          'Kelvingrove',
          'Garnethill',
          'Charing Cross',
          'Cowcaddens',
          'Townhead',
          'Calton',
          'Bridgeton'
        ]
      },
      'Wales': {
        'Cardiff': [
          'Queen Street',
          'St. Mary Street',
          'High Street',
          'Castle Street',
          'Church Street',
          'Cathays',
          'Roath',
          'Canton',
          'Grangetown',
          'Butetown',
          'Adamsdown',
          'Splott',
          'Tremorfa',
          'Rumney',
          'Llanrumney',
          'Llanedeyrn',
          'Pentwyn',
          'Llanishen',
          'Thornhill',
          'Lisvane'
        ]
      }
    },
    'Canada': {
      'Ontario': {
        'Toronto': [
          'Yonge Street',
          'Queen Street',
          'King Street',
          'Bloor Street',
          'Dundas Street',
          'College Street',
          'Spadina Avenue',
          'Bathurst Street',
          'Ossington Avenue',
          'Dufferin Street',
          'Queen West',
          'King West',
          'Entertainment District',
          'Financial District',
          'Distillery District',
          'Kensington Market',
          'Chinatown',
          'Little Italy',
          'Greektown',
          'Little India'
        ],
        'Ottawa': [
          'Wellington Street',
          'Sparks Street',
          'Bank Street',
          'Elgin Street',
          'Rideau Street',
          'Sussex Drive',
          'ByWard Market',
          'Centretown',
          'Westboro',
          'Hintonburg',
          'Glebe',
          'Sandy Hill',
          'Rockcliffe Park',
          'New Edinburgh',
          'Vanier',
          'Overbrook',
          'Alta Vista',
          'Billings Bridge',
          'Heron Park',
          'Riverside South'
        ]
      },
      'Quebec': {
        'Montreal': [
          'Saint Catherine Street',
          'Saint Denis Street',
          'Saint Laurent Boulevard',
          'Sherbrooke Street',
          'Mount Royal Avenue',
          'Parc Avenue',
          'Crescent Street',
          'Peel Street',
          'McGill Street',
          'University Street',
          'Old Montreal',
          'Plateau Mont-Royal',
          'Mile End',
          'Outremont',
          'Westmount',
          'NDG',
          'Verdun',
          'Lachine',
          'LaSalle',
          'Ahuntsic'
        ]
      },
      'British Columbia': {
        'Vancouver': [
          'Robson Street',
          'Granville Street',
          'West Georgia Street',
          'Hastings Street',
          'Commercial Drive',
          'Main Street',
          'Cambie Street',
          'Oak Street',
          'Arbutus Street',
          'West Broadway',
          'Gastown',
          'Yaletown',
          'Chinatown',
          'West End',
          'Kitsilano',
          'Mount Pleasant',
          'Strathcona',
          'Commercial-Broadway',
          'Metrotown',
          'Richmond'
        ]
      }
    },
    'Australia': {
      'New South Wales': {
        'Sydney': [
          'George Street',
          'Pitt Street',
          'Castlereagh Street',
          'Macquarie Street',
          'Circular Quay',
          'The Rocks',
          'Darling Harbour',
          'Bondi Beach',
          'Manly Beach',
          'Coogee Beach',
          'Surry Hills',
          'Paddington',
          'Glebe',
          'Newtown',
          'Balmain',
          'Rozelle',
          'Leichhardt',
          'Marrickville',
          'Redfern',
          'Waterloo'
        ]
      },
      'Victoria': {
        'Melbourne': [
          'Collins Street',
          'Bourke Street',
          'Flinders Street',
          'Swanston Street',
          'Elizabeth Street',
          'Chapel Street',
          'Brunswick Street',
          'Smith Street',
          'Lygon Street',
          'Acland Street',
          'Fitzroy',
          'Carlton',
          'Northcote',
          'Thornbury',
          'Preston',
          'Brunswick',
          'Coburg',
          'Footscray',
          'Yarraville',
          'Williamstown'
        ]
      },
      'Queensland': {
        'Brisbane': [
          'Queen Street',
          'Adelaide Street',
          'Edward Street',
          'George Street',
          'Albert Street',
          'Wickham Street',
          'Fortitude Valley',
          'West End',
          'South Bank',
          'Kangaroo Point',
          'New Farm',
          'Teneriffe',
          'Bulimba',
          'Hawthorne',
          'East Brisbane',
          'Woolloongabba',
          'Highgate Hill',
          'Dutton Park',
          'Fairfield',
          'Annerley'
        ]
      }
    },
    'Japan': {
      'Tokyo': {
        'Tokyo': [
          'Ginza',
          'Shibuya Crossing',
          'Harajuku',
          'Akihabara',
          'Shinjuku',
          'Shibuya',
          'Roppongi',
          'Omotesando',
          'Aoyama',
          'Ebisu',
          'Daikanyama',
          'Nakameguro',
          'Jiyugaoka',
          'Kichijoji',
          'Shimokitazawa',
          'Koenji',
          'Nakano',
          'Ikebukuro',
          'Ueno',
          'Asakusa'
        ]
      },
      'Osaka': {
        'Osaka': [
          'Dotonbori',
          'Shinsaibashi',
          'Namba',
          'Umeda',
          'Tennoji',
          'Nipponbashi',
          'Amerikamura',
          'Horie',
          'Nishi-Shinsaibashi',
          'Minami',
          'Kita',
          'Chuo',
          'Naniwa',
          'Tennoji',
          'Abeno',
          'Ikuno',
          'Higashisumiyoshi',
          'Nishinari',
          'Taisho',
          'Konohana'
        ]
      }
    },
    'South Korea': {
      'Seoul': {
        'Seoul': [
          'Gangnam',
          'Myeongdong',
          'Hongdae',
          'Itaewon',
          'Insadong',
          'Dongdaemun',
          'Namdaemun',
          'Gwanghwamun',
          'Yeouido',
          'Jamsil',
          'Songpa',
          'Gangdong',
          'Gangseo',
          'Yangcheon',
          'Guro',
          'Geumcheon',
          'Yeongdeungpo',
          'Gangnam',
          'Seocho',
          'Mapo'
        ]
      }
    }
  };

  // Get all countries
  static List<String> getCountries() {
    return _locationData.keys.toList()..sort();
  }

  // Get districts for a specific country
  static List<String> getDistricts(String country) {
    final countryData = _locationData[country];
    if (countryData == null) return [];
    return countryData.keys.toList()..sort();
  }

  // Get cities for a specific country and district
  static List<String> getCities(String country, String district) {
    final countryData = _locationData[country];
    if (countryData == null) return [];
    
    final districtData = countryData[district];
    if (districtData == null) return [];
    
    return districtData.keys.toList()..sort();
  }

  // Get streets for a specific country, district, and city
  static List<String> getStreets(String country, String district, String city) {
    final countryData = _locationData[country];
    if (countryData == null) return [];
    
    final districtData = countryData[district];
    if (districtData == null) return [];
    
    final cityData = districtData[city];
    if (cityData == null) return [];
    
    return cityData..sort();
  }

  // Get governorates for a specific country, district, and city (same as streets for now)
  static List<String> getGovernorates(String country, String district, String city) {
    return getStreets(country, district, city);
  }

  // Validate if a location combination exists
  static bool isValidLocation(String country, String district, String city, String street) {
    final streets = getStreets(country, district, city);
    return streets.contains(street);
  }
} 